# Generated by Django 5.2.9 on 2026-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_gamehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='moves',
            field=models.JSONField(default=list),
        ),
    ]
